[features]
seeds = false
skip-lint = false
[programs.localnet]
mycalculatordapp = "D2uC9UFFwGXZoCMQW1UvRYvKeWCj5UyZcZJkYH18dccv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/panthsolanki/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
